### ISSUE TITLE
SVM is not created until .fit() is called and cannot be serialized/deserialized.

### ISSUE THREAD

**Issue by notadamking** [machinelearnjs/machinelearnjs#168]
* **I'm submitting a ...**
[ x] bug report

* **Summary**

Due to the asynchronous nature of creating an SVM, the decision has been made to not instantiate an SVM until the asynchronous fit() method is called. This not only feels incorrect, it prevents the deserialization of previous SVMs. This is part of the reason why the .toJSON() and .fromJSON() methods do not work.

I have a PR in the works to fix this.

**Comment by JasonShin** [comment]
@adamjking3 wow I really appreciate you again for this! Just by reading the issue description, the current SVM implementation totally doesn't make sense haha... sorry I couldn't pick this up when I was implementing initially!

I will take a look at your PR now!

**Comment by JasonShin** [comment]
Unrelated to the PR that you've submitted, but I'd like to ask for some feedback/thoughts. It sounds like you've been using Kalimdor's SVMs, and it would be perfect to find out your overall feelings about the SVM APIs.

I thought we should build SVMs from scratch if we want to have full control over its implementation and most importantly, make it GPU accelerated. 

_Questions:_
1) Do you think libsvm-js is sufficient enough in the long run?
2) Should we write SVMs from scratch using tfjs-core?

**Comment by adamjking3** [comment]
1. Since it doesn't look like libsvm-js has any plans to support GPU acceleration, I would assume it is insufficient.
2. GPU acceleration would improve my use case, so I am biased to say yes.

**Comment by JasonShin** [comment]
@benjaminmcdonald is willing to implement SVMs from scratch, but we will work on it together. Would you like to join as well? @adamjking3

**Comment by JasonShin** [comment]
I thought about this for a while, I think we will clone `libsvm-js` and fully refactor it to suit machinelearn.js. I'm currently working on this at https://github.com/machinelearnjs/libsvm-ts

**Comment by JasonShin** [comment]
Closing it. Now you can use loadASM or loasWASM
