### ISSUE TITLE
Usage improvements -> fixing some errors

### ISSUE THREAD

**Issue by JasonShin** [machinelearnjs/machinelearnjs#233]
* **I'm submitting a ...**
[/] bug report

* **Summary**
I realised there are a few issues that you encounter when you try to use machinelearn.js

1. libsvm.js might prevent `npm install` if the project does not have `git init` already run
2. Cannot use the module unless you install `fs-extra`
3. tensorflow.js warning still shows up when using the library

**Comment by JasonShin** [comment]
I fixed the installation issue caused by libsvm by cloning the project at https://github.com/machinelearnjs/libsvm-ts

**Comment by VariableVasasMT** [comment]
I will pick `Tensor.buffer() is renamed to Tensor.bufferSync()` warnings

**Comment by JasonShin** [comment]
@VariableVasasMT thanks =)

**Comment by JasonShin** [comment]
I'm going to close this for now and reopen another ticket to disable to TF warning messages
