### ISSUE TITLE
Fix yarn test:unit Errors

### ISSUE THREAD

**Issue by kamalesh0406** [machinelearnjs/machinelearnjs#235]
* **I'm submitting a ...**
[\ ] bug report
[ ] feature request
[ ] question about the decisions made in the repository
[ ] question about how to use this project

* **Summary**
Running yarn test:unit returns errors in tests associated with 10 test files. Commits to fix each of these errors will be referenced to this issye

**Comment by JasonShin** [comment]
Closing this as we've already discussed on Telegram =)
